async function main() {
  console.log('Hello, world!')
}

main().catch((error) => {
  console.error('An error occurred:', error)
  process.exit(1)
})
